<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vladimir-HP" name="com.example.tests.TestOfGroupCreation" tests="5" failures="0" timestamp="30 Nov 2015 20:02:16 GMT" time="8.603" errors="2">
  <testcase name="testGroupCreationWithValidData" time="2.095" classname="com.example.tests.TestOfGroupCreation"/>
  <testcase name="testGroupCreationWithValidData" time="0.666" classname="com.example.tests.TestOfGroupCreation">
    <error type="java.lang.AssertionError" message="
Expected: &lt;[GroupData [id=44, name=, header=Test2, footer=test0], GroupData [id=null, name=test1, header=Test2, footer=test0], GroupData [id=45, name=test2, header=Test1, footer=]]&gt;
     but: was &lt;[GroupData [id=44, name=, header=Test2, footer=test0], GroupData [id=45, name=test2, header=Test1, footer=]]&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: <[GroupData [id=44, name=, header=Test2, footer=test0], GroupData [id=null, name=test1, header=Test2, footer=test0], GroupData [id=45, name=test2, header=Test1, footer=]]]]><![CDATA[>
     but: was <[GroupData [id=44, name=, header=Test2, footer=test0], GroupData [id=45, name=test2, header=Test1, footer=]]]]><![CDATA[>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.example.tests.TestOfGroupCreation.testGroupCreationWithValidData(TestOfGroupCreation.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testGroupCreationWithValidData -->
  <testcase name="deleteAllGroups" time="1.319" classname="com.example.tests.TestOfGroupCreation"/>
  <testcase name="testGroupCreationWithValidData" time="2.241" classname="com.example.tests.TestOfGroupCreation">
    <error type="java.lang.AssertionError" message="
Expected: &lt;[GroupData [id=44, name=, header=Test2, footer=test0], GroupData [id=null, name=, header=Test2, footer=test0], GroupData [id=45, name=test2, header=Test1, footer=]]&gt;
     but: was &lt;[GroupData [id=44, name=, header=Test2, footer=test0], GroupData [id=47, name=, header=Test2, footer=test0], GroupData [id=46, name=test1, header=Test2, footer=test0], GroupData [id=45, name=test2, header=Test1, footer=]]&gt;">
      <![CDATA[java.lang.AssertionError: 
Expected: <[GroupData [id=44, name=, header=Test2, footer=test0], GroupData [id=null, name=, header=Test2, footer=test0], GroupData [id=45, name=test2, header=Test1, footer=]]]]><![CDATA[>
     but: was <[GroupData [id=44, name=, header=Test2, footer=test0], GroupData [id=47, name=, header=Test2, footer=test0], GroupData [id=46, name=test1, header=Test2, footer=test0], GroupData [id=45, name=test2, header=Test1, footer=]]]]><![CDATA[>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:956)
	at org.junit.Assert.assertThat(Assert.java:923)
	at com.example.tests.TestOfGroupCreation.testGroupCreationWithValidData(TestOfGroupCreation.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </error>
  </testcase> <!-- testGroupCreationWithValidData -->
  <testcase name="testGroupCreationWithValidData" time="2.282" classname="com.example.tests.TestOfGroupCreation"/>
</testsuite> <!-- com.example.tests.TestOfGroupCreation -->
